### ISSUE TITLE
[feat] Start9 UI Support

### ISSUE THREAD

**Issue by kn0wmad** [deverickapollo/hundredsats#1]
Hi there - would love to see your UI available on the Monero node I packaged up for [Start9 Servers](https://github.com/kn0wmad/monerod-wrapper).  The config section would not be required (or likely compatible) since Start9 already has a highly functional config system built into the OS.  Can we chat about what would be required to get this ported over?

StartOS offers many advantages over docker-compose projects, including SSL support, backups, `s9pk` side-loading, and instant access for users via the Community Registry (no need to add "app stores" for every project).

**Comment by deverickapollo** [comment]
Unfortunately, its source is protected by @getumbrel copyright as it is a fork of preexisting work from the bitcoin app. I'm not sure Start9 is able to use the code for another commercial product. Ideally, a new design is created to fit the Start9 brand. 

Technically speaking, the app just needs RPC access to the node so likely not much required to get it working. My dms are open on twitter or telegram @deverickapollo if you want to continue the discussion.  I'll close this as resolved.
